"""How a pack sources its document *content* — and whether that needs a key.

The one thing that decides if a document type can be generated on a laptop with
no cloud account is where its prose comes from. Invoices are procedural: every
description, company and figure is drawn from a built-in catalogue and computed,
so a full dataset generates offline and deterministically. A contract is not —
its clauses, recitals and defined terms are generated natural language, and there
is no procedural substitute at quality, so an LLM is effectively required.

That makes "local-first" a property of the **pack**, not a promise of the
platform, and this module makes the distinction explicit rather than tribal
knowledge: a pack *declares* its :class:`ContentMode`, and the kernel can report
it, gate on it, and drive the LLM path when there is one.

The infrastructure around a pack (storage, run state, export) still defaults to
local for either mode — only content generation differs.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from docloom.core.providers.base import CompletionResult
    from docloom.core.providers.budget import BudgetGuard
    from docloom.core.providers.catalogue_runner import CatalogueItem, RunReport
    from docloom.core.providers.mix import ProviderMix
    from docloom.core.usage.base import UsageSink


class ContentMode(StrEnum):
    """Where a pack's document content comes from."""

    #: Built in and computed — deterministic, offline, no API key. The whole
    #: dataset can be generated on one machine.
    PROCEDURAL = "procedural"
    #: Generated by an LLM in a one-time, offline catalogue step. Needs a
    #: provider and a key; the document run itself still makes no LLM calls.
    LLM_BACKED = "llm_backed"


@dataclass(frozen=True, slots=True)
class ContentCapability:
    """A pack's declared content-generation profile."""

    mode: ContentMode
    notes: str = ""

    @property
    def requires_api_key(self) -> bool:
        """True when producing this pack's content needs a provider credential."""
        return self.mode is ContentMode.LLM_BACKED

    @property
    def local_first(self) -> bool:
        """True when a full dataset can be generated with no cloud account.

        Exactly the procedural case — the property the README scopes to the
        invoice pack rather than claiming for the platform.
        """
        return self.mode is ContentMode.PROCEDURAL


#: The default for a pack that predates this contract: assume procedural, since
#: an LLM-backed pack cannot work without deliberately wiring a provider anyway.
PROCEDURAL_DEFAULT = ContentCapability(ContentMode.PROCEDURAL)


def capability_of(pack: object) -> ContentCapability:
    """A pack's :class:`ContentCapability`, defaulting to procedural.

    Read defensively so a third-party pack written before this contract existed
    still loads — the kernel keeps narrow expectations of packs.
    """
    return getattr(pack, "content_capability", PROCEDURAL_DEFAULT)


@runtime_checkable
class LlmContentBuilder(Protocol):
    """The extra contract an :attr:`ContentMode.LLM_BACKED` pack implements.

    Two halves of the offline catalogue step: say what needs generating, then
    take the generated text back. Deliberately not part of
    :class:`~docloom.core.pack.DocumentPack` — a procedural pack should not have
    to stub these out.
    """

    def catalogue_items(self) -> list[CatalogueItem]:
        """Every content ask for the catalogue build, each with a stable id."""
        ...

    def ingest(self, results: Mapping[str, CompletionResult]) -> None:
        """Take the generated text (keyed by item id) into the pack's catalogue."""
        ...


async def build_catalogue(
    pack: object,
    mix: ProviderMix,
    *,
    budget: BudgetGuard | None = None,
    concurrency: int = 8,
    use_batch: bool = True,
    usage: UsageSink | None = None,
) -> RunReport:
    """Run an LLM-backed pack's offline catalogue step.

    Drives the pack's items through the weighted provider mix under the budget
    — batching the batch-capable slice — then hands the results back to the pack.
    Raises for a procedural pack, which has no catalogue to build.

    ``usage`` records what each call cost. Catalogue calls are attributed to the
    *item* they generated, not a document: one item is reused across many
    documents, so per-document cost from a catalogue build is amortised rather
    than measured.
    """
    from docloom.core.providers.catalogue_runner import CatalogueRunner

    capability = capability_of(pack)
    if capability.mode is not ContentMode.LLM_BACKED:
        raise ValueError(
            f"{getattr(pack, 'name', pack)!r} is {capability.mode} — it has no LLM "
            "catalogue to build; its content is generated locally"
        )
    if not isinstance(pack, LlmContentBuilder):
        raise TypeError(
            f"{getattr(pack, 'name', pack)!r} declares {ContentMode.LLM_BACKED} but does "
            "not implement LlmContentBuilder (catalogue_items / ingest)"
        )
    runner = CatalogueRunner(mix, budget=budget, concurrency=concurrency,
                             use_batch=use_batch, usage=usage)
    report = await runner.run(pack.catalogue_items())
    pack.ingest(report.results)
    return report
